# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Lokanta Vihara
tagline:          'The Monastery at the End of the World'
description:      'Two monks. One space. Looming apocalypse. What could go wrong?'
url:              https://lokanta.github.io/
baseurl:           https://lokanta.github.io/

author:
  name:           'Bhikkhu Sujato'
  url:            https://suttacentral.net/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/lokanta

theme: jekyll-theme-minimal
